version: '2'
services:
  nginx:
    build: nginx
    ports:
      - 80:80
    volumes:
      - ./dist:/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
