export enum CompoundPropertiesTooltips {
  mw_freebase = 'Molecular weight of parent compound',
  alogp = 'Calculated ALogP',
  hba = 'Number hydrogen bond acceptors',
  hbd = 'Number hydrogen bond donors',
  psa = 'Polar surface area',
  rtb = 'Number rotatable bonds',
  ro3_pass = 'Indicates whether the compound passes the rule-of-three (mw < 300, logP < 3 etc)',
  num_ro5_violations = 'Number of violations of Lipinski\'s rule-of-five, using HBA and HBD definitions',
  acd_most_apka = 'The most acidic pKa calculated using ACDlabs v12.01',
  acd_most_bpka = 'The most basic pKa calculated using ACDlabs v12.01',
  acd_logp = 'The calculated octanol/water partition coefficient using ACDlabs v12.01',
  acd_logd = 'The calculated octanol/water distribution coefficient at pH7.4 using ACDlabs v12.01',
  molecular_species = 'Indicates whether the compound is an acid/base/neutral',
  full_mwt = 'Molecular weight of the full compound including any salts',
  aromatic_rings = 'Number of aromatic rings',
  heavy_atoms = 'Number of heavy (non-hydrogen) atoms',
  num_alerts = 'Number of structural alerts for QED calculation (as defined by Brenk et al., ChemMedChem 2008)',
  qed_weighted = 'Weighted quantitative estimate of drug likeness (as defined by Bickerton et al., Nature Chem 2012)',
  mw_monoisotopic = 'Monoisotopic parent molecular weight',
  full_molformula = 'Molecular formula for the full compound (including any salt)',
  hba_lipinski = "Number of hydrogen bond acceptors calculated according to Lipinski's original rules (i.e., N + O count))",
  hbd_lipinski = "Number of hydrogen bond donors calculated according to Lipinski's original rules (i.e., NH + OH count)",
  num_lipinski_ro5_violations = "Number of violations of Lipinski's rule of five using HBA_LIPINSKI and HBD_LIPINSKI counts",
}
